workspace:
  base: /go
  path: src/github.com/sundryp/drone-test
  
pipeline:
  build:
    image: docker:17.03.0-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker version

  build2:
    image: gcc
    commands:
      - ls -al ~
      - pwd


